# Generated by Django 2.0.3 on 2018-03-30 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('type_of_submission', models.CharField(choices=[('CG', 'Curriculum Guide'), ('TK', 'Assignment Task'), ('WB', 'Workbook')], max_length=3)),
                ('grade', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('dat_link', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphics', models.TextField(verbose_name='Pairing graphics with words')),
                ('concrete', models.TextField(verbose_name='Linking abstract concepts with concrete representations')),
                ('probing', models.TextField(verbose_name='Posing probing questions')),
                ('elaboration', models.TextField(verbose_name='Elaboration Interrogation')),
                ('solved_problems', models.TextField(verbose_name='Repeatedly alternating solved and unsolved problems')),
                ('practice', models.TextField(verbose_name='Retrieval and Distributed Practice')),
                ('originality', models.TextField()),
                ('typo_errors', models.TextField()),
                ('deepness', models.TextField()),
                ('comprehensible', models.TextField()),
                ('overall_comments', models.TextField()),
                ('dat_link', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
